{% set python_min = "3.10" %}
{% set name = "hyp3lib" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4e7e37156934bbd0aed6844903954c1925ab2c9987e314649bd40ce2c636bf7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - byteSigmaScale.py = hyp3lib.byteSigmaScale:main
    - createAmp.py = hyp3lib.createAmp:main
    - get_orb.py = hyp3lib.get_orb:main
    - makeAsfBrowse.py = hyp3lib.makeAsfBrowse:main
    - make_cogs.py = hyp3lib.make_cogs:main
    - raster_boundary2shape.py = hyp3lib.raster_boundary2shape:main
    - resample_geotiff.py = hyp3lib.resample_geotiff:main
    - rtc2color.py = hyp3lib.rtc2color:main
    - SLC_copy_S1_fullSW.py = hyp3lib.SLC_copy_S1_fullSW:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - python-build
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - boto3 >=1.36.0
    - gdal
    - lxml
    - netCDF4
    - numpy
    - pillow
    - requests
    - scipy
    - statsmodels
    - urllib3

test:
  requires:
    - python {{ python_min }}
  imports:
    - hyp3lib
  commands:
    - byteSigmaScale.py --help
    - createAmp.py --help
    - get_orb.py --help
    - makeAsfBrowse.py --help
    - make_cogs.py --help
    - raster_boundary2shape.py --help
    - resample_geotiff.py --help
    - rtc2color.py --help
    - SLC_copy_S1_fullSW.py --help
    # legacy scripts
    - GC_map_mod --help

about:
  home: https://github.com/ASFHyP3/hyp3-lib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Common library for HyP3 plugins

extra:
  recipe-maintainers:
    - williamh890
    - andrewplayer3
    - jhkennedy
    - asjohnston-asf
    - forrestfwilliams
    - jtherrmann
    - jacquelynsmale
